set nocompatible	" Use Vim full features, first option to be set because it changes many other options

" Vim will load $VIMRUNTIME/defaults.vim if the user does not have a vimrc.
" This happens after /etc/vimrc{.local} are loaded, so it will override any settings in these files.
" If you don't want that to happen, uncomment the below line to prevent defaults.vim from being loaded.
let g:skip_defaults_vim = 1

" Vim5 and later versions support syntax highlighting. Uncommenting the next line enables syntax highlighting by default.
syntax on

" If using a dark background within the editing area and syntax highlighting turn on this option as well
set background=dark

" Uncomment the following to have Vim jump to the last position when reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins according to the detected filetype.
"if has("autocmd")
filetype plugin indent on
"endif

set backspace=indent,eol,start	"more powerful basckspace
set history=50		" Save 50 last commands lines
let c_comment_strings=1 " Highlight string in c comments
set laststatus=2	" Always show status line
set statusline=%f%m%r%h%w%y%=%l,%c,%p%%	" Customize status line
set wildmenu		" Enable enhanced menu for command line completion
"set cursorcolumn	" highlight cursor column
"set cursorline		" highlight cursor line
"set ruler		" Show cursor position
set wrap		" Enable long lines to wrap
set wrapscan		" search wrap around end of file
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set showmode		" Show actual editing mode
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden		" Hide buffers when they are abandoned
set mouse=a		" Enable mouse usage (all modes)
set shiftwidth=4	" Tabs uses 4 spaces
set foldcolumn=1	" columns to view foldable text
set smarttab		" uses shiftwidth spaces as tab (backspace delete many spaces)
set scrolloff=5		" minimum screen lines to keep above and below the cursor
set foldmethod=syntax	" Use folding based on syntax file
"set complete=".,w,b,u,i"	" Search for a match for autocomplete in current buffer, included files including defined names
