#!/bin/bash

#version 2.2.53

extract $0
./configure --prefix=/usr --bindir=/bin --disable-static --libexecdir=/usr/lib --docdir=/usr/share/doc/acl-2.2.53 &&
make -j $procs &&
make -j $procs install &&
mv -v /usr/lib/libacl.so.* /lib &&
ln -sfv /lib/$(readlink /usr/lib/libacl.so) /usr/lib/libacl.so &&
remove $0
