#!/bin/bash

#version 2.4.48

extract $0 &&
./configure --prefix=/usr --bindir=/bin --disable-static --sysconfdir=/etc --docdir=/usr/share/doc/attr-2.4.48 &&
make -j $procs &&
make -j $procs install &&
mv -vf /usr/lib/libattr.so.* /lib &&
ln -sfv /lib/$(readlink /usr/lib/libattr.so) /usr/lib/libattr.so &&
remove $0
