#!/bin/bash

#version 4.4

. $(dirname $_)/lib &&
extract ${1}sources $0 $2 &&
./configure --prefix=/tools --without-bash-malloc &&
make -j $3 &&
make -j $3 install &&
ln -sv bash /tools/bin/sh &&
remove ${1}sources $0 $2