#!/bin/bash +h

#version 1.07.1

extract $0 &&
echo "#! /bin/bash
sed -e '1   s/^/{\"/' -e 's/$/\",/' -e '2,$ s/^/\"/' -e '$ d' -i libmath.h
sed -e '$ s/$/0}/' -i libmath.h" > bc/fix-libmath_h &&
ln -svf /tools/lib/libncursesw.so.6 /usr/lib/libncursesw.so.6 &&
ln -sfv libncurses.so.6 /usr/lib/libncurses.so &&
sed -i -e '/flex/s/as_fn_error/: ;; # &/' configure &&
./configure --prefix=/usr --with-readline --mandir=/usr/share/man --infodir=/usr/share/info &&
make -j $procs &&
make -j $procs install &&
remove $0
