#!/bin/bash +h

#version 3.0.5

extract $0 &&
if [ $1 -eq 1 ]; then ./configure --prefix=/tools
elif [ $1 -eq 2 ]; then ./configure --prefix=/usr --docdir=/usr/share/doc/bison-3.0.5
fi &&
make -j $procs &&
make -j $procs install &&
remove $0
