#!/bin/bash +h

#version 8.3

cp -v /alfs/etc/sysconfig/{static.ifconfig.example,console,rc.site} /etc/sysconfig/ &&
cp -v /alfs/etc/{resolv.conf,hostname,hosts,inittab,clock,profile,inputrc,shells,fstab} /etc/
