#!/bin/bash

#version 8.26

. $(dirname $_)/lib &&
extract ${1}sources $0 $2 &&
./configure --prefix=/tools --enable-install-program=hostname &&
make -j $3 &&
make -j $3 install &&
remove ${1}sources $0 $2