#!/bin/bash

#version 8.30

extract $0 &&
if [ $# -eq 0 || $1 -eq 1 ]; then ./configure --prefix=/tools --enable-install-program=hostname
elif [ $1 -eq 2 ]; then
    patch -Np1 -i ../coreutils-8.30-i18n-1.patch &&
    sed -i '/test.lock/s/^/#/' gnulib-tests/gnulib.mk &&
    autoreconf -fiv &&
    export FORCE_UNSAFE_CONFIGURE=1 &&
    ./configure --prefix=/usr --enable-no-install-program=kill,uptime
fi &&
make -j $procs &&
make -j $procs install &&
if [ $1 -eq 2 ]; then
    mv -v /usr/bin/{cat,chgrp,chmod,chown,cp,date,dd,df,echo} /bin &&
    mv -v /usr/bin/{false,ln,ls,mkdir,mknod,mv,pwd,rm} /bin &&
    mv -v /usr/bin/{rmdir,stty,sync,true,uname} /bin &&
    mv -v /usr/bin/chroot /usr/sbin &&
    mv -v /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8 &&
    sed -i s/\"1\"/\"8\"/1 /usr/share/man/man8/chroot.8 &&
    mv -v /usr/bin/{head,sleep,nice} /bin
fi &&
remove $0
