#!/bin/bash

#version 3.6

extract $0 &&
if [ $1 -eq 1 ]; then ./configure --prefix=/tools
elif [ $1 -eq 2 ]; then ./configure --prefix=/usr
fi &&
make -j $procs &&
make -j $procs install &&
remove $0
