#!/tools/bin/bash -h

cp -v /alfs/etc/passwd /etc/passwd &&
cp -v /alfs/etc/group /etc/group &&
mkdir -pv /{bin,boot,etc/{opt,sysconfig},home,lib/firmware,mnt,opt} &&
mkdir -pv /{media/{floppy,cdrom},sbin,srv,var} &&
install -dv -m 0750 /root &&
install -dv -m 1777 /tmp /var/tmp &&
mkdir -pv /usr/{,local/}{bin,include,lib,sbin,src} &&
mkdir -pv /usr/{,local/}share/{color,dict,doc,info,locale,man} &&
mkdir -pv /usr/{,local/}share/{misc,terminfo,zoneinfo} &&
mkdir -pv /usr/libexec &&
mkdir -pv /usr/{,local/}share/man/man{1..8} &&
mkdir -pv /lib64 &&
mkdir -pv /var/{log,mail,spool} &&
ln -svf /run /var/run &&
ln -svf /run/lock /var/lock &&
mkdir -pv /var/{opt,cache,lib/{color,misc,locate},local} &&
ln -svf /tools/bin/{bash,cat,dd,echo,ln,pwd,rm,stty} /bin &&
ln -svf /tools/bin/{env,install,perl} /usr/bin &&
ln -svf /tools/lib/libgcc_s.so{,.1} /usr/lib &&
ln -svf /tools/lib/libstdc++.{a,so{,.6}} /usr/lib &&
for lib in blkid lzma mount uuid
do
    ln -svf /tools/lib/lib${lib}.so* /usr/lib || exit 1
done &&
ln -svf /tools/include/blkid /usr/include &&
ln -svf /tools/include/libmount /usr/include &&
ln -svf /tools/include/uuid /usr/include &&
install -vdm755 /usr/lib/pkgconfig &&
for pc in blkid mount uuid
do
    sed 's@tools@usr@g' /tools/lib/pkgconfig/${pc}.pc > /usr/lib/pkgconfig/${pc}.pc || exit 1
done &&
ln -svf bash /bin/sh &&
ln -svf /proc/self/mounts /etc/mtab &&
touch /var/log/{btmp,lastlog,faillog,wtmp} &&
chgrp -v utmp /var/log/lastlog &&
chmod -v 664  /var/log/lastlog &&
chmod -v 600  /var/log/btmp
