#!/bin/bash +h

#version 2.2.6

extract $0 &&
sed -i 's|usr/bin/env |bin/|' run.sh.in &&
./configure --prefix=/usr --disable-static --docdir=/usr/share/doc/expat-2.2.6 &&
make -j $procs &&
make -j $procs install &&
install -v -m644 doc/*.{html,png,css} /usr/share/doc/expat-2.2.6 &&
remove $0
