#!/bin/bash +h

#version 5.45.4

extract $0 &&
cp -v configure{,.orig} &&
sed -i 's:/usr/local/bin:/bin:' configure &&
./configure --prefix=/tools --with-tcl=/tools/lib --with-tclinclude=/tools/include &&
make -j $procs &&
make -j $procs SCRIPTS="" install &&
remove $0
