#!/bin/bash

#version 4.6.0

extract $0 &&
sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' gl/lib/*.c &&
sed -i '/unistd/a #include <sys/sysmacros.h>' gl/lib/mountlist.c &&
echo "#define _IO_IN_BACKUP 0x100" >> gl/lib/stdio-impl.h &&
if [ $1 -eq 1 ]; then ./configure --prefix=/tools
elif [ $1 -eq 2 ]; then
    sed -i 's/test-lock..EXEEXT.//' tests/Makefile.in &&
    ./configure --prefix=/usr --localstatedir=/var/lib/locate
fi &&
make -j $procs &&
make -j $procs install &&
if [ $1 -eq 2 ]; then
    mv -v /usr/bin/find /bin &&
    sed -i 's|find:=${BINDIR}|find:=/bin|' /usr/bin/updatedb
fi &&
remove $0
