#!/bin/bash

#version 2.6.4

extract $0 &&
sed -i "/math.h/a #include <malloc.h>" src/flexdef.h &&
HELP2MAN=/tools/bin/true &&
./configure --prefix=/usr --docdir=/usr/share/doc/flex-2.6.4 &&
make -j $procs &&
make -j $procs install &&
ln -sv flex /usr/bin/lex &&
remove $0
