#!/bin/bash

#version 0.19.8.1

extract $0 &&
pushd gettext-tools &&
EMACS="no" ./configure --prefix=/tools --disable-shared &&
make -j $procs -C gnulib-lib &&
make -j $procs -C intl pluralx.c &&
make -j $procs -C src msgfmt &&
make -j $procs -C src msgmerge &&
make -j $procs -C src xgettext &&
cp -v src/{msgfmt,msgmerge,xgettext} /tools/bin &&
remove $0
