#!/bin/bash

#version 6.1.2

. $(dirname $_)/lib &&
extract /sources $0 $2 &&
./configure --prefix=/usr    \
            --enable-cxx     \
            --disable-static \
            --docdir=/usr/share/doc/gmp-6.1.2 &&
make -j $3 &&
make -j $3 html &&
make check 2>&1 | tee gmp-check-log &&
if [[ ! $(awk '/# PASS:/{total+=$3} ; END{print total}' gmp-check-log) =~ 190 ]]; then echo $0 'test suite failed!'; exit 1; fi &&
make -j $3 install &&
make -j $3 install-html &&
remove /sources $0 $2