#!/bin/bash +h

#version 3.1

extract $0 &&
if [ $1 -eq 1 ]; then ./configure --prefix=/tools
elif [ $1 -eq 2 ]; then ./configure --prefix=/usr --bindir=/bin
fi &&
make -j $procs &&
make -j $procs install &&
remove $0
