#!/bin/bash

#version 1.9

extract $0 &&
sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c &&
echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h &&
if [ $1 -eq 1 ]; then ./configure --prefix=/tools
elif [ $1 -eq 2 ]; then ./configure --prefix=/usr
fi &&
make -j $procs &&
make -j $procs install &&
if [ $1 -eq 2 ]; then mv -vf /usr/bin/gzip /bin; fi &&
remove $0
