#!/bin/bash

#version 4.18.0

extract $0 &&
sed -i /ARPD/d Makefile &&
rm -fv man/man8/arpd.8 &&
sed -i 's/.m_ipt.o//' tc/Makefile &&
make -j $procs &&
make -j $procs DOCDIR=/usr/share/doc/iproute2-4.18.0 install &&
remove $0
