#!/bin/bash +h

#version 2.0.4

extract $0 &&
patch -Np1 -i ../kbd-2.0.4-backspace-1.patch &&
sed -i 's/\(RESIZECONS_PROGS=\)yes/\1no/g' configure &&
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in &&
export PKG_CONFIG_PATH=/tools/lib/pkgconfig &&
./configure --prefix=/usr --disable-vlock &&
make -j $procs &&
make -j $procs install &&
mkdir -pv /usr/share/doc/kbd-2.0.4 &&
cp -rv docs/doc/* /usr/share/doc/kbd-2.0.4 &&
remove $0
