#!/bin/bash

#version 25

extract $0 &&
./configure --prefix=/usr --bindir=/bin --sysconfdir=/etc --with-rootlibdir=/lib --with-xz --with-zlib &&
make -j $procs &&
make -j $procs install &&
for target in depmod insmod lsmod modinfo modprobe rmmod
do
    ln -sfv /bin/kmod /sbin/$target || exit 1
done &&
ln -sfv kmod /bin/lsmod &&
remove $0
