#!/bin/bash

#TO BE REMOVED, NO LONGER REQUIRED
#CSV file l count
#Parameter 1: CSV file
#Output: Number of columns
function column_count
{
        local columns=0
        local x=0
        local y=0
        until [ $x -gt $(wc -l $1 | cut -d ' ' -f 1) ]
        do
                (( x++ ))
                y=$(sed "${x}q;d" $1 | tr ',' ' ' | wc -w | cut -d ' ' -f 1)
                if [ $y -gt $columns ]; then columns=$y; fi
        done &&
        echo $columns
}

#find archive name from package name in package download urls file
#arg1: package name
#output: archive name
function find_archive
{
	grep "^$1" $packs | cut -f 2 | rev | cut -d '/' -f 1 | rev
}

#find tar archive root directory name from package name in sources working directory
#arg1: package name
#output: archive root directory
function tar_root
{
	tar -tf ${wdir}sources/$(find_archive $1) | sed '1q;d' | cut -d '/' -f 1
}

#cd to sources working directory, decompress, untar package and cd to root directory of the archive
#arg1: package to extract
function extract
{
	pushd ${wdir}sources &&
	tar -xvf $(find_archive $1) &&
	pushd $(tar_root $1)
}

#exit extracted package directory and remove it
#arg1: package name
function remove
{
	cd ~-0 && #change to directory at the bottom of the stack
	dirs -c && #clear the directory stack
	rm -rvf ${wdir}sources/$(tar_root $1)
}

#testing purpose only
function hello
{
    echo 'hello world!' &&
    echo "wdir from function in lib file: $wdir"
}

#export functions to subshells
export -f find_archive tar_root extract remove hello
