#!/bin/bash +h

#TO BE REMOVED, NO LONGER REQUIRED
#CSV file l count
#Parameter 1: CSV file
#Output: Number of columns
function column_count
{
        local columns=0
        local x=0
        local y=0
        until [ $x -gt $(wc -l $1 | cut -d ' ' -f 1) ]
        do
                (( x++ ))
                y=$(sed "${x}q;d" $1 | tr ',' ' ' | wc -w | cut -d ' ' -f 1)
                if [ $y -gt $columns ]; then columns=$y; fi
        done &&
        echo $columns
}

#find archive name from package name in package download urls file
#arg1: package name
#output: archive name
function find_archive
{
    grep "^$(basename $1)[[:blank:]]" $packs | cut -f 2 | rev | cut -d '/' -f 1 | rev
}

#find tar archive root directory name from package name in sources working directory
#arg1: package name
#output: archive root directory
function tar_root
{
    tar -tf ${wdir}sources/$(find_archive $(basename $1)) | sed '1q;d' | cut -d '/' -f 1
}

#cd to sources working directory, decompress, untar package and cd to root directory of the archive
#arg1: package name
function extract
{
    pushd ${wdir}sources &&
    tar -xvf $(find_archive $(basename $1)) &&
    pushd $(tar_root $(basename $1))
}

#exit extracted package directory and remove it
#arg1: package name
function remove
{
    cd ~-0 && #change to directory at the bottom of the stack
    dirs -c && #clear the directory stack
    rm -rvf ${wdir}sources/$(tar_root $(basename $1))
}

#evaluate words from args environment variable
#exit status: 0 if evaluation is succesfull, otherwise an error code >= 1
function arg_eval
{
    if [ ${args[0]:-''} = '' ]; then return 1; fi && #invalid package script/name
    args[1]=${args[1]:-1} #replace args[1] by 1 if unset or null
}

#testing purpose only
function hello
{
    echo 'hello world!' &&
    echo "wdir from function in lib file: $wdir"
}

#export functions to subshells
export -f find_archive tar_root extract remove hello
