#!/bin/bash +h

#version 2.25

extract $0 &&
sed -i '/install.*STALIBNAME/d' libcap/Makefile &&
make -j $procs &&
make RAISE_SETFCAP=no lib=lib prefix=/usr install &&
chmod -v 755 /usr/lib/libcap.so &&
mv -vf /usr/lib/libcap.so.* /lib &&
ln -sfv /lib/$(readlink /usr/lib/libcap.so) /usr/lib/libcap.so &&
remove $0
