#!/bin/bash

#version 6.3.0

. $(dirname $_)/lib &&
extract ${1}sources gcc $2 &&
mkdir -v build &&
pushd build &&
../libstdc++-v3/configure           \
    --host=$LFS_TGT                 \
    --prefix=/tools                 \
    --disable-multilib              \
    --disable-nls                   \
    --disable-libstdcxx-threads     \
    --disable-libstdcxx-pch         \
    --with-gxx-include-dir=/tools/${LFS_TGT}/include/c++/6.3.0 &&
make -j $3 &&
make -j $3 install &&
remove ${1}sources gcc $2