#!/bin/bash +h

#version 4.18.5

extract $0 &&
make -j $procs mrproper &&
if [ $1 -eq 1 -o $1 -eq 2 ]; then make -j $procs INSTALL_HDR_PATH=dest headers_install
elif [ $1 -eq 3 ]; then
    make -j $procs menuconfig
fi &&
if [ $1 -eq 1 ]; then #first pass
    cp -rv dest/include/* /tools/include
elif [ $1 -eq 2 ]; then #second pass
    find dest/include \( -name .install -o -name ..install.cmd \) -delete &&
    cp -rv dest/include/* /usr/include
elif [ $1 -eq 3 ]; then
    make -j $procs &&
    #make -j $procs modules_install && #install modules (in /lib/modules) if you use them in your configuration
    cp -iv arch/x86/boot/bzImage /boot/vmlinuz-4.18.5-lfs-8.3 && #aasuming x86 architecture
    cp -iv System.map /boot/System.map-4.18.5 && #install map file
    cp -iv .config /boot/config-4.18.5 && #keep config for future reference
    install -d /usr/share/doc/linux-4.18.5 &&
    cp -rv Documentation/* /usr/share/doc/linux-4.18.5
fi &&
remove $0
