#!/bin/bash

#version 4.18.5

extract $0 &&
make -j $procs mrproper &&
if [ $# -eq 0 || $1 -eq 1 ]; then #first pass
    make -j $procs INSTALL_HDR_PATH=dest headers_install &&
    cp -rv dest/include/* /tools/include
elif [ $1 -eq 2 ]; then #second pass
    find dest/include \( -name .install -o -name ..install.cmd \) -delete &&
    cp -rv dest/include/* /usr/include
fi &&
remove $0
