#!/bin/bash

#version 4.10

. $(dirname $_)/lib &&
extract ${1}sources $0 $2 &&
make -j $3 mrproper &&
if [ $# -eq 3 || $4 -eq 1 ]; then
make -j $3 INSTALL_HDR_PATH=dest headers_install &&
cp -rv dest/include/* /tools/include
elif [ $4 -eq 2 ]; then
find dest/include \( -name .install -o -name ..install.cmd \) -delete &&
cp -rv dest/include/* /usr/include
fi &&
remove ${1}sources $0 $2