#!/bin/bash

#version 1.4.18

extract $0 &&
sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c &&
echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h &&
./configure --prefix=/tools &&
make -j $procs &&
make -j $procs install &&
remove $0
