#!/bin/bash +h

#version 4.2.1

extract $0 &&
sed -i '211,217 d; 219,229 d; 232 d' glob/glob.c &&
if [ $1 -eq 1 ]; then ./configure --prefix=/tools --without-guile
elif [ $1 -eq 2 ]; then ./configure --prefix=/usr
fi &&
make -j $procs &&
make -j $procs install &&
remove $0
