#!/bin/bash

#version 2.8.4

extract $0 &&
./configure --prefix=/usr --docdir=/usr/share/doc/man-db-2.8.4 --sysconfdir=/etc --disable-setuid --enable-cache-owner=bin --with-browser=/usr/bin/lynx --with-vgrind=/usr/bin/vgrind --with-grap=/usr/bin/grap --with-systemdtmpfilesdir= &&
make -j $procs &&
make -j $procs install &&
remove $0
