#!/bin/bash +h

#version 1.1.0

extract $0 &&
./configure --prefix=/usr --disable-static --docdir=/usr/share/doc/mpc-1.1.0 &&
make -j $procs &&
make -j $procs html &&
make -j $procs install &&
make -j $procs install-html &&
remove $0
