#!/bin/bash

#version 4.0.1

extract $0 &&
./configure --prefix=/usr --disable-static --enable-thread-safe --docdir=/usr/share/doc/mpfr-4.0.1 &&
make -j $procs &&
make -j $procs html &&
make -j $procs check &&
make -j $procs install &&
make -j $procs install-html &&
remove $0
