#!/bin/bash

#version 6.0

. $(dirname $_)/lib &&
extract ${1}sources $0 $2 &&
if [ $# -eq 3 || $4 -eq 1 ]; then
sed -i s/mawk// configure &&
./configure --prefix=/tools \
            --with-shared   \
            --without-debug \
            --without-ada   \
            --enable-widec  \
            --enable-overwrite
elif [ $4 -eq 2 ]; then
sed -i '/LIBTOOL_INSTALL/d' c++/Makefile.in &&
./configure --prefix=/usr           \
            --mandir=/usr/share/man \
            --with-shared           \
            --without-debug         \
            --without-normal        \
            --enable-pc-files       \
            --enable-widec
fi &&
make -j $3 &&
make -j $3 install &&
if [ $4 -eq 2 ]; then
mv -v /usr/lib/libncursesw.so.6* /lib &&
ln -sfv /lib/$(readlink /usr/lib/libncursesw.so) /usr/lib/libncursesw.so &&
for lib in ncurses form panel menu
do
	rm -vf /usr/lib/lib${lib}.so &&
	echo "INPUT(-l${lib}w)" > /usr/lib/lib${lib}.so &&
	ln -sfv ${lib}w.pc /usr/lib/pkgconfig/${lib}.pc || { echo $0 'script failed!'; exit 1; }
done &&
rm -vf /usr/lib/libcursesw.so &&
echo "INPUT(-lncursesw)" > /usr/lib/libcursesw.so &&
ln -sfv libncurses.so /usr/lib/libcurses.so
fi &&
remove ${1}sources $0 $2