#!/bin/bash

#version 1.1.0i

extract $0 &&
./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib shared zlib-dynamic &&
make -j $procs &&
sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile &&
make -j $procs MANSUFFIX=ssl install &&
mv -vf /usr/share/doc/openssl /usr/share/doc/openssl-1.1.0i &&
cp -vfr doc/* /usr/share/doc/openssl-1.1.0i &&
remove $0
