#!/bin/bash

#version 5.24.1

. $(dirname $_)/lib &&
extract ${1}sources $0 $2 &&
sh Configure -des -Dprefix=/tools -Dlibs=-lm &&
make -j $3 &&
cp -v perl cpan/podlators/scripts/pod2man /tools/bin &&
mkdir -pv /tools/lib/perl5/5.24.1 &&
cp -Rv lib/* /tools/lib/perl5/5.24.1 &&
remove ${1}sources $0 $2