#!/bin/bash

#version 0.29.2

extract $0 &&
./configure --prefix=/usr --with-internal-glib --disable-host-tool --docdir=/usr/share/doc/pkg-config-0.29.2 &&
make -j $procs &&
make -j $procs install &&
remove $0
