#!/bin/bash

#version 0.29.1

. $(dirname $_)/lib &&
extract ${1}sources $0 $2 &&
./configure --prefix=/usr              \
            --with-internal-glib       \
            --disable-compile-warnings \
            --disable-host-tool        \
            --docdir=/usr/share/doc/pkg-config-0.29.1 &&
make -j $3 &&
make -j $3 install &&
remove ${1}sources $0 $2