#!/bin/bash

#version 3.3.15

extract $0 &&
./configure --prefix=/usr --exec-prefix= --libdir=/usr/lib --docdir=/usr/share/doc/procps-ng-3.3.15 --disable-static --disable-kill &&
make -j $procs &&
make -j $procs install &&
mv -vf /usr/lib/libprocps.so.* /lib &&
ln -sfv /lib/$(readlink /usr/lib/libprocps.so) /usr/lib/libprocps.so &&
remove $0
