#!/bin/bash

#version 8.3

#strip libraries
strip --strip-debug /tools/lib/* &&
#strip binaries
/usr/bin/strip --strip-unneeded /tools/{,s}bin/* &&
#remove documentation
rm -rvf /tools/{,share}/{info,man,doc} &&
#remove unnedded files
find /tools/{lib,libexec} -name \*.la -delete
