#!/bin/bash

#version 8.6.8

extract $0 &&
pushd unix &&
./configure --prefix=/tools &&
make -j $procs &&
make -j $procs install &&
chmod -v u+w /tools/lib/libtcl8.6.so &&
make -j $procs install-private-headers &&
ln -sv tclsh8.6 /tools/bin/tclsh &&
remove $0
