#!/bin/bash

#testing purpose only

echo "script name: $0
sdir: $sdir
wdir: $wdir
deps: $deps
packs: $packs
procs: $procs
arg1: $1" &&
hello &&
export test=hello &&
${sdir}test2 &&
echo 'test script success'
