#!/bin/bash +h

#testing purpose only

echo "script name: $0
sdir: $sdir
wdir: $wdir
deps: $deps
packs: $packs
procs: $procs
arg1: $1
args[1]: ${args[1]}
SHELLOPTS: $SHELLOPTS" &&
hello &&
echo "$0 script success"
