#!/bin/bash

#version 6.5

extract $0 &&
if [ $1 -eq 1 ]; then ./configure --prefix=/tools
elif [ $1 -eq 2 ]; then
    sed -i '5481,5485 s/({/(\\{/' tp/Texinfo/Parser.pm &&
    ./configure --prefix=/usr --disable-static
fi &&
make -j $procs &&
make -j $procs install &&
remove $0
