#!/bin/bash

#version 8.3

#change owner of tools to root to prevent user from altering it
sudo chown -Rv root: ${wdir}tools &&
#create directories of virtual kernel filesystems
sudo mkdir -pv ${wdir}{dev,proc,sys,run} &&
#create required devices nodes
sudo mknod -m 600 ${wdir}dev/console c 5 1 &&
sudo mknod -m 666 ${wdir}dev/null c 1 3 &&
#bind mount /dev from host
sudo mount -v --bind /dev ${wdir}dev &&
sudo mount -vt devpts devpts ${wdir}dev/pts -o gid=5,mode=620 &&
sudo mount -vt proc proc ${wdir}proc &&
sudo mount -vt sysfs sysfs ${wdir}sys &&
sudo mount -vt tmpfs tmpfs ${wdir}run &&
#create a directory if a symbolic link that point to it exists
if [ -h ${wdir}dev/shm ]; then sudo mkdir -pv ${wdir}$(readlink ${wdir}dev/shm); fi &&
#copy alfs directory to new root
#dependencies and package urls files must be in the same directory as scripts directory
sudo cp -rv ${sdir}.. ${wdir}alfs &&
#enter chroot and continue executing scripts
sudo chroot $wdir /tools/bin/bash /alfs/scripts/alfs / /alfs/$(basename $deps) /alfs/$(basename $packs) $procs '#preparing#2'
#do not continue executing other scripts because they were executed in the previous command
echo 'transition script failed! message below can be safely ignored...' &&
exit 1 #tell caller that this script has failed
