#!/bin/bash

sudo chown -R root: ${1}tools &&
sudo mkdir -pv ${1}{dev,proc,sys,run} &&
sudo mknod -m 600 ${1}dev/console c 5 1 &&
sudo mknod -m 666 ${1}dev/null c 1 3 &&
sudo mount -v --bind /dev ${1}dev &&
sudo mount -vt devpts devpts ${1}dev/pts -o gid=5,mode=620 &&
sudo mount -vt proc proc ${1}proc &&
sudo mount -vt sysfs sysfs ${1}sys &&
sudo mount -vt tmpfs tmpfs ${1}run &&
if [ -h ${1}dev/shm ]; then sudo mkdir -pv ${1}$(readlink ${1}dev/shm); fi &&
#Copy alfs directory to new root
sudo cp -rv $(dirname $2) ${1}alfs &&
#Enter chroot and continue executing scripts
sudo chroot $1 /tools/bin/bash /alfs/scripts/alfs / /alfs/$(basename $csv) /alfs/$(basename $urls) $3 '#preparing#2'
#Do not continue executing other scripts because they were executed in the previous command
break 2