#!/bin/bash

#version 8.3

#copy alfs directory to new root
#dependencies and package urls files must be in the same directory as scripts directory
sudo cp -rv ${sdir}.. ${wdir}alfs &&
#enter chroot and continue executing scripts
sudo chroot $wdir /tools/bin/env -i HOME=/root TERM="$TERM" PS1='\u:\w\$ ' PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin /tools/bin/bash /alfs/scripts/alfs / /alfs/$(basename $deps) /alfs/$(basename $packs) $procs '#preparing#2' &&
#do not continue executing other scripts because they were executed in the previous command
echo 'transition script failed! message below can be safely ignored...' &&
exit 1 #tell caller that this script has failed
