#!/bin/bash

#version 2.32.1

extract $0 &&
./configure --prefix=/tools --without-python --disable-makeinstall-chown --without-systemdsystemunitdir --without-ncurses PKG_CONFIG="" &&
make -j $procs &&
make -j $procs install &&
remove $0
