#!/bin/bash +h

#version 8.1

extract $0 &&
echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h &&
./configure --prefix=/usr &&
make -j $procs &&
make -j $procs install &&
ln -svf vim /usr/bin/vi &&
for L in /usr/share/man/{,*/}man1/vim.1
do
    ln -svf vim.1 $(dirname $L)/vi.1 || exit 1
done &&
ln -svf /usr/share/vim/vim81/doc /usr/share/doc/vim-8.1 &&
cp -v /alfs/etc/vimrc /etc/vimrc &&
remove $0
