#!/bin/bash

#version 1.2.11

. $(dirname $_)/lib &&
extract /sources $0 $2 &&
./configure --prefix=/usr &&
make -j $3 &&
make -j $3 install &&
mv -v /usr/lib/libz.so.* /lib &&
ln -sfv /lib/$(readlink /usr/lib/libz.so) /usr/lib/libz.so &&
remove /sources $0 $2